{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "viola-test-api.fullname" . }}
  labels:
    {{- include "viola-test-api.labels" . | nindent 4 }}
{{- end -}}
